
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 07 15:30:22 GMT-03:00 2016
//----------------------------------------------------

package doxa.version1;

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */	
	public static final int MENOR_QUE = 12;
	public static final int MAIOR_QUE = 13;
	public static final int MENOR_IGUAL = 14;
	public static final int MAIOR_IGUAL = 15;
	public static final int IGUAL = 16;
	public static final int DIFERENTE = 17;
	
	public static final int MAIS = 8;
	public static final int MENOS = 9;
	public static final int VEZES = 3;
	public static final int DIVISAO = 18;
	public static final int MODULO = 19;
	public static final int AND = 20;
	public static final int OR = 21;
	public static final int NOT = 22;
	
	public static final int ATRIBUICAO = 7;
	
	public static final int FECHA_PAR = 6;
	public static final int ABRE_PAR = 5;
	public static final int VIRGULA = 23;
	public static final int PT_VIRG = 4;
	public static final int ABRE_CHAVES = 24;
	public static final int FECHA_CHAVES = 25;
	
	public static final int IF = 26;
	public static final int ELSE = 27;
	public static final int WHILE = 28;
	public static final int RETURN = 29;
	public static final int FLOAT = 30;
	public static final int CHAR = 31;
	public static final int VOID = 32;
	public static final int PRNT = 33;
	public static final int INT = 34;
	public static final int PROC = 35;
	public static final int VAR = 36;
	
	public static final int INT_LITERAL = 10;
	public static final int FLOAT_LITERAL = 37;
	public static final int CHAR_LITERAL = 38;
	
	public static final int IDENTIFICADOR = 11;
	public static final int EOF = 0;
	public static final int error = 1;
}
